esphome:
  name: "esphome-wth"
  friendly_name: ESPHome WTH
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev
  platformio_options:
   build_flags:
     - "-std=gnu++17"
   build_unflags:
     - "-std=gnu++11"
     - "-fno-rtti"  

esp32:
  board: wt32-eth01
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: "1c5ca30876ad5fa36bf20a0762c12da9"

time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

#  entity_room_temperature: "sensor.durchschnittstemperatur_haus_ohne_keller"
#  entity_humidity: "sensor.durchschnitt_luftfeuchtigkeit_haus"

#########################################
#                                       #
#   Ethernet Konfiguration              #
#                                       #
#########################################
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

#########################################
#                                       #
#   SPI configuration                   #
#                                       #
#########################################
spi:
  id: McpSpi
  clk_pin: GPIO15
  mosi_pin: GPIO14
  miso_pin: GPIO12

#########################################
#                                       #
#   CAN configuration                   #
#                                       #
#########################################
canbus:
  - id: !extend wp_can
    platform: mcp2515
    spi_id: McpSpi
    cs_pin: GPIO04

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
  #  energymeter: !include OneESP32ToRuleThemAll/yaml/energymeter.yaml
  #  watermeter: !include OneESP32ToRuleThemAll/yaml/watermeter.yaml
  #sensors: !include OneESP32ToRuleThemAll/yaml/sensors.yaml
  # thz404: !include OneESP32ToRuleThemAll/yaml/thz404.yaml
  #thz504: !include OneESP32ToRuleThemAll/yaml/thz504.yaml
# thz55eco: !include OneESP32ToRuleThemAll/yaml/thz5_5_eco.yaml
 ttf07: !include OneESP32ToRuleThemAll/yaml/ttf07.yaml
#  kondensatpumpe: !include OneESP32ToRuleThemAll/yaml/kondensatpumpe.yaml

